/**
 * This class is generated by jOOQ
 */
package com.wenwu.tables;


import com.wenwu.tables.tables.SCourse;
import com.wenwu.tables.tables.SCourseHistory;
import com.wenwu.tables.tables.SCourseJoin;
import com.wenwu.tables.tables.SCourseQuestion;
import com.wenwu.tables.tables.SCourseware;
import com.wenwu.tables.tables.SUserAccount;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in db_wenwu
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>db_wenwu.s_course</code>.
     */
    public static final SCourse S_COURSE = com.wenwu.tables.tables.SCourse.S_COURSE;

    /**
     * The table <code>db_wenwu.s_courseware</code>.
     */
    public static final SCourseware S_COURSEWARE = com.wenwu.tables.tables.SCourseware.S_COURSEWARE;

    /**
     * The table <code>db_wenwu.s_course_history</code>.
     */
    public static final SCourseHistory S_COURSE_HISTORY = com.wenwu.tables.tables.SCourseHistory.S_COURSE_HISTORY;

    /**
     * The table <code>db_wenwu.s_course_join</code>.
     */
    public static final SCourseJoin S_COURSE_JOIN = com.wenwu.tables.tables.SCourseJoin.S_COURSE_JOIN;

    /**
     * The table <code>db_wenwu.s_course_question</code>.
     */
    public static final SCourseQuestion S_COURSE_QUESTION = com.wenwu.tables.tables.SCourseQuestion.S_COURSE_QUESTION;

    /**
     * The table <code>db_wenwu.s_user_account</code>.
     */
    public static final SUserAccount S_USER_ACCOUNT = com.wenwu.tables.tables.SUserAccount.S_USER_ACCOUNT;
}
