/**
 * This class is generated by jOOQ
 */
package com.wenwu.tables.tables;


import com.wenwu.tables.DbWenwu;
import com.wenwu.tables.Keys;
import com.wenwu.tables.tables.records.SCourseHistoryRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SCourseHistory extends TableImpl<SCourseHistoryRecord> {

    private static final long serialVersionUID = -1873757123;

    /**
     * The reference instance of <code>db_wenwu.s_course_history</code>
     */
    public static final SCourseHistory S_COURSE_HISTORY = new SCourseHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SCourseHistoryRecord> getRecordType() {
        return SCourseHistoryRecord.class;
    }

    /**
     * The column <code>db_wenwu.s_course_history.id</code>.
     */
    public final TableField<SCourseHistoryRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_course_history.create_time</code>.
     */
    public final TableField<SCourseHistoryRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>db_wenwu.s_course_history.course_id</code>.
     */
    public final TableField<SCourseHistoryRecord, Integer> COURSE_ID = createField("course_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_course_history.status</code>.
     */
    public final TableField<SCourseHistoryRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_course_history.grade</code>.
     */
    public final TableField<SCourseHistoryRecord, Integer> GRADE = createField("grade", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_course_history.unknown_num</code>.
     */
    public final TableField<SCourseHistoryRecord, Integer> UNKNOWN_NUM = createField("unknown_num", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>db_wenwu.s_course_history</code> table reference
     */
    public SCourseHistory() {
        this("s_course_history", null);
    }

    /**
     * Create an aliased <code>db_wenwu.s_course_history</code> table reference
     */
    public SCourseHistory(String alias) {
        this(alias, S_COURSE_HISTORY);
    }

    private SCourseHistory(String alias, Table<SCourseHistoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private SCourseHistory(String alias, Table<SCourseHistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbWenwu.DB_WENWU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SCourseHistoryRecord, Integer> getIdentity() {
        return Keys.IDENTITY_S_COURSE_HISTORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SCourseHistoryRecord> getPrimaryKey() {
        return Keys.KEY_S_COURSE_HISTORY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SCourseHistoryRecord>> getKeys() {
        return Arrays.<UniqueKey<SCourseHistoryRecord>>asList(Keys.KEY_S_COURSE_HISTORY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseHistory as(String alias) {
        return new SCourseHistory(alias, this);
    }

    /**
     * Rename this table
     */
    public SCourseHistory rename(String name) {
        return new SCourseHistory(name, null);
    }
}
