/**
 * This class is generated by jOOQ
 */
package com.wenwu.tables.tables;


import com.wenwu.tables.DbWenwu;
import com.wenwu.tables.Keys;
import com.wenwu.tables.tables.records.SCourseJoinRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SCourseJoin extends TableImpl<SCourseJoinRecord> {

    private static final long serialVersionUID = -1156515479;

    /**
     * The reference instance of <code>db_wenwu.s_course_join</code>
     */
    public static final SCourseJoin S_COURSE_JOIN = new SCourseJoin();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SCourseJoinRecord> getRecordType() {
        return SCourseJoinRecord.class;
    }

    /**
     * The column <code>db_wenwu.s_course_join.id</code>.
     */
    public final TableField<SCourseJoinRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_course_join.course_id</code>.
     */
    public final TableField<SCourseJoinRecord, Integer> COURSE_ID = createField("course_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_course_join.u_id</code>.
     */
    public final TableField<SCourseJoinRecord, Integer> U_ID = createField("u_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_course_join.join_time</code>.
     */
    public final TableField<SCourseJoinRecord, Timestamp> JOIN_TIME = createField("join_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>db_wenwu.s_course_join</code> table reference
     */
    public SCourseJoin() {
        this("s_course_join", null);
    }

    /**
     * Create an aliased <code>db_wenwu.s_course_join</code> table reference
     */
    public SCourseJoin(String alias) {
        this(alias, S_COURSE_JOIN);
    }

    private SCourseJoin(String alias, Table<SCourseJoinRecord> aliased) {
        this(alias, aliased, null);
    }

    private SCourseJoin(String alias, Table<SCourseJoinRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbWenwu.DB_WENWU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SCourseJoinRecord, Integer> getIdentity() {
        return Keys.IDENTITY_S_COURSE_JOIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SCourseJoinRecord> getPrimaryKey() {
        return Keys.KEY_S_COURSE_JOIN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SCourseJoinRecord>> getKeys() {
        return Arrays.<UniqueKey<SCourseJoinRecord>>asList(Keys.KEY_S_COURSE_JOIN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseJoin as(String alias) {
        return new SCourseJoin(alias, this);
    }

    /**
     * Rename this table
     */
    public SCourseJoin rename(String name) {
        return new SCourseJoin(name, null);
    }
}
