/**
 * This class is generated by jOOQ
 */
package com.wenwu.tables.tables;


import com.wenwu.tables.DbWenwu;
import com.wenwu.tables.Keys;
import com.wenwu.tables.tables.records.SCourseRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SCourse extends TableImpl<SCourseRecord> {

    private static final long serialVersionUID = -1850358324;

    /**
     * The reference instance of <code>db_wenwu.s_course</code>
     */
    public static final SCourse S_COURSE = new SCourse();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SCourseRecord> getRecordType() {
        return SCourseRecord.class;
    }

    /**
     * The column <code>db_wenwu.s_course.id</code>.
     */
    public final TableField<SCourseRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_course.course_name</code>.
     */
    public final TableField<SCourseRecord, String> COURSE_NAME = createField("course_name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_course.course_describe</code>.
     */
    public final TableField<SCourseRecord, String> COURSE_DESCRIBE = createField("course_describe", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_course.logo</code>.
     */
    public final TableField<SCourseRecord, String> LOGO = createField("logo", org.jooq.impl.SQLDataType.VARCHAR.length(150), this, "");

    /**
     * The column <code>db_wenwu.s_course.create_time</code>.
     */
    public final TableField<SCourseRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_course.status</code>.
     */
    public final TableField<SCourseRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_course.u_id</code>.
     */
    public final TableField<SCourseRecord, Integer> U_ID = createField("u_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>db_wenwu.s_course</code> table reference
     */
    public SCourse() {
        this("s_course", null);
    }

    /**
     * Create an aliased <code>db_wenwu.s_course</code> table reference
     */
    public SCourse(String alias) {
        this(alias, S_COURSE);
    }

    private SCourse(String alias, Table<SCourseRecord> aliased) {
        this(alias, aliased, null);
    }

    private SCourse(String alias, Table<SCourseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbWenwu.DB_WENWU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SCourseRecord, Integer> getIdentity() {
        return Keys.IDENTITY_S_COURSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SCourseRecord> getPrimaryKey() {
        return Keys.KEY_S_COURSE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SCourseRecord>> getKeys() {
        return Arrays.<UniqueKey<SCourseRecord>>asList(Keys.KEY_S_COURSE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourse as(String alias) {
        return new SCourse(alias, this);
    }

    /**
     * Rename this table
     */
    public SCourse rename(String name) {
        return new SCourse(name, null);
    }
}
