/**
 * This class is generated by jOOQ
 */
package com.wenwu.tables.tables;


import com.wenwu.tables.DbWenwu;
import com.wenwu.tables.Keys;
import com.wenwu.tables.tables.records.SCoursewareRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SCourseware extends TableImpl<SCoursewareRecord> {

    private static final long serialVersionUID = 1481448581;

    /**
     * The reference instance of <code>db_wenwu.s_courseware</code>
     */
    public static final SCourseware S_COURSEWARE = new SCourseware();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SCoursewareRecord> getRecordType() {
        return SCoursewareRecord.class;
    }

    /**
     * The column <code>db_wenwu.s_courseware.id</code>.
     */
    public final TableField<SCoursewareRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_courseware.courseware_name</code>.
     */
    public final TableField<SCoursewareRecord, String> COURSEWARE_NAME = createField("courseware_name", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_courseware.content</code>.
     */
    public final TableField<SCoursewareRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.VARCHAR.length(300).nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_courseware.url</code>.
     */
    public final TableField<SCoursewareRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(150).nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_courseware.size</code>.
     */
    public final TableField<SCoursewareRecord, Integer> SIZE = createField("size", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_courseware.status</code>.
     */
    public final TableField<SCoursewareRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db_wenwu.s_courseware.course_id</code>.
     */
    public final TableField<SCoursewareRecord, Integer> COURSE_ID = createField("course_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>db_wenwu.s_courseware</code> table reference
     */
    public SCourseware() {
        this("s_courseware", null);
    }

    /**
     * Create an aliased <code>db_wenwu.s_courseware</code> table reference
     */
    public SCourseware(String alias) {
        this(alias, S_COURSEWARE);
    }

    private SCourseware(String alias, Table<SCoursewareRecord> aliased) {
        this(alias, aliased, null);
    }

    private SCourseware(String alias, Table<SCoursewareRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbWenwu.DB_WENWU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SCoursewareRecord, Integer> getIdentity() {
        return Keys.IDENTITY_S_COURSEWARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SCoursewareRecord> getPrimaryKey() {
        return Keys.KEY_S_COURSEWARE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SCoursewareRecord>> getKeys() {
        return Arrays.<UniqueKey<SCoursewareRecord>>asList(Keys.KEY_S_COURSEWARE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseware as(String alias) {
        return new SCourseware(alias, this);
    }

    /**
     * Rename this table
     */
    public SCourseware rename(String name) {
        return new SCourseware(name, null);
    }
}
