/**
 * This class is generated by jOOQ
 */
package com.wenwu.tables.tables.records;


import com.wenwu.tables.tables.SCourseHistory;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SCourseHistoryRecord extends UpdatableRecordImpl<SCourseHistoryRecord> implements Record6<Integer, Timestamp, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1469454854;

    /**
     * Setter for <code>db_wenwu.s_course_history.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course_history.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_wenwu.s_course_history.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course_history.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>db_wenwu.s_course_history.course_id</code>.
     */
    public void setCourseId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course_history.course_id</code>.
     */
    public Integer getCourseId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>db_wenwu.s_course_history.status</code>.
     */
    public void setStatus(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course_history.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>db_wenwu.s_course_history.grade</code>.
     */
    public void setGrade(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course_history.grade</code>.
     */
    public Integer getGrade() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>db_wenwu.s_course_history.unknown_num</code>.
     */
    public void setUnknownNum(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course_history.unknown_num</code>.
     */
    public Integer getUnknownNum() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SCourseHistory.S_COURSE_HISTORY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return SCourseHistory.S_COURSE_HISTORY.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return SCourseHistory.S_COURSE_HISTORY.COURSE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return SCourseHistory.S_COURSE_HISTORY.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return SCourseHistory.S_COURSE_HISTORY.GRADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return SCourseHistory.S_COURSE_HISTORY.UNKNOWN_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getUnknownNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseHistoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseHistoryRecord value2(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseHistoryRecord value3(Integer value) {
        setCourseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseHistoryRecord value4(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseHistoryRecord value5(Integer value) {
        setGrade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseHistoryRecord value6(Integer value) {
        setUnknownNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseHistoryRecord values(Integer value1, Timestamp value2, Integer value3, Integer value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SCourseHistoryRecord
     */
    public SCourseHistoryRecord() {
        super(SCourseHistory.S_COURSE_HISTORY);
    }

    /**
     * Create a detached, initialised SCourseHistoryRecord
     */
    public SCourseHistoryRecord(Integer id, Timestamp createTime, Integer courseId, Integer status, Integer grade, Integer unknownNum) {
        super(SCourseHistory.S_COURSE_HISTORY);

        set(0, id);
        set(1, createTime);
        set(2, courseId);
        set(3, status);
        set(4, grade);
        set(5, unknownNum);
    }
}
