/**
 * This class is generated by jOOQ
 */
package com.wenwu.tables.tables.records;


import com.wenwu.tables.tables.SCourse;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SCourseRecord extends UpdatableRecordImpl<SCourseRecord> implements Record7<Integer, String, String, String, Timestamp, Integer, Integer> {

    private static final long serialVersionUID = 379332955;

    /**
     * Setter for <code>db_wenwu.s_course.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_wenwu.s_course.course_name</code>.
     */
    public void setCourseName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course.course_name</code>.
     */
    public String getCourseName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db_wenwu.s_course.course_describe</code>.
     */
    public void setCourseDescribe(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course.course_describe</code>.
     */
    public String getCourseDescribe() {
        return (String) get(2);
    }

    /**
     * Setter for <code>db_wenwu.s_course.logo</code>.
     */
    public void setLogo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course.logo</code>.
     */
    public String getLogo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>db_wenwu.s_course.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>db_wenwu.s_course.status</code>.
     */
    public void setStatus(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>db_wenwu.s_course.u_id</code>.
     */
    public void setUId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course.u_id</code>.
     */
    public Integer getUId() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, Timestamp, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, Timestamp, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SCourse.S_COURSE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SCourse.S_COURSE.COURSE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SCourse.S_COURSE.COURSE_DESCRIBE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SCourse.S_COURSE.LOGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return SCourse.S_COURSE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return SCourse.S_COURSE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return SCourse.S_COURSE.U_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCourseName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCourseDescribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLogo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getUId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseRecord value2(String value) {
        setCourseName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseRecord value3(String value) {
        setCourseDescribe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseRecord value4(String value) {
        setLogo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseRecord value5(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseRecord value6(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseRecord value7(Integer value) {
        setUId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SCourseRecord
     */
    public SCourseRecord() {
        super(SCourse.S_COURSE);
    }

    /**
     * Create a detached, initialised SCourseRecord
     */
    public SCourseRecord(Integer id, String courseName, String courseDescribe, String logo, Timestamp createTime, Integer status, Integer uId) {
        super(SCourse.S_COURSE);

        set(0, id);
        set(1, courseName);
        set(2, courseDescribe);
        set(3, logo);
        set(4, createTime);
        set(5, status);
        set(6, uId);
    }
}
