/**
 * This class is generated by jOOQ
 */
package com.wenwu.tables.tables.records;


import com.wenwu.tables.tables.SCourseware;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SCoursewareRecord extends UpdatableRecordImpl<SCoursewareRecord> implements Record7<Integer, String, String, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 367446050;

    /**
     * Setter for <code>db_wenwu.s_courseware.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_wenwu.s_courseware.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_wenwu.s_courseware.courseware_name</code>.
     */
    public void setCoursewareName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_wenwu.s_courseware.courseware_name</code>.
     */
    public String getCoursewareName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db_wenwu.s_courseware.content</code>.
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_wenwu.s_courseware.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>db_wenwu.s_courseware.url</code>.
     */
    public void setUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_wenwu.s_courseware.url</code>.
     */
    public String getUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>db_wenwu.s_courseware.size</code>.
     */
    public void setSize(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_wenwu.s_courseware.size</code>.
     */
    public Integer getSize() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>db_wenwu.s_courseware.status</code>.
     */
    public void setStatus(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_wenwu.s_courseware.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>db_wenwu.s_courseware.course_id</code>.
     */
    public void setCourseId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>db_wenwu.s_courseware.course_id</code>.
     */
    public Integer getCourseId() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, Integer, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, Integer, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SCourseware.S_COURSEWARE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SCourseware.S_COURSEWARE.COURSEWARE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SCourseware.S_COURSEWARE.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SCourseware.S_COURSEWARE.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return SCourseware.S_COURSEWARE.SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return SCourseware.S_COURSEWARE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return SCourseware.S_COURSEWARE.COURSE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCoursewareName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCoursewareRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCoursewareRecord value2(String value) {
        setCoursewareName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCoursewareRecord value3(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCoursewareRecord value4(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCoursewareRecord value5(Integer value) {
        setSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCoursewareRecord value6(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCoursewareRecord value7(Integer value) {
        setCourseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCoursewareRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SCoursewareRecord
     */
    public SCoursewareRecord() {
        super(SCourseware.S_COURSEWARE);
    }

    /**
     * Create a detached, initialised SCoursewareRecord
     */
    public SCoursewareRecord(Integer id, String coursewareName, String content, String url, Integer size, Integer status, Integer courseId) {
        super(SCourseware.S_COURSEWARE);

        set(0, id);
        set(1, coursewareName);
        set(2, content);
        set(3, url);
        set(4, size);
        set(5, status);
        set(6, courseId);
    }
}
