/**
 * This class is generated by jOOQ
 */
package com.wenwu.tables.tables.records;


import com.wenwu.tables.tables.SCourseJoin;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SCourseJoinRecord extends UpdatableRecordImpl<SCourseJoinRecord> implements Record4<Integer, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = -199756612;

    /**
     * Setter for <code>db_wenwu.s_course_join.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course_join.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_wenwu.s_course_join.course_id</code>.
     */
    public void setCourseId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course_join.course_id</code>.
     */
    public Integer getCourseId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>db_wenwu.s_course_join.u_id</code>.
     */
    public void setUId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course_join.u_id</code>.
     */
    public Integer getUId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>db_wenwu.s_course_join.join_time</code>.
     */
    public void setJoinTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course_join.join_time</code>.
     */
    public Timestamp getJoinTime() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SCourseJoin.S_COURSE_JOIN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SCourseJoin.S_COURSE_JOIN.COURSE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return SCourseJoin.S_COURSE_JOIN.U_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return SCourseJoin.S_COURSE_JOIN.JOIN_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getJoinTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseJoinRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseJoinRecord value2(Integer value) {
        setCourseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseJoinRecord value3(Integer value) {
        setUId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseJoinRecord value4(Timestamp value) {
        setJoinTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseJoinRecord values(Integer value1, Integer value2, Integer value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SCourseJoinRecord
     */
    public SCourseJoinRecord() {
        super(SCourseJoin.S_COURSE_JOIN);
    }

    /**
     * Create a detached, initialised SCourseJoinRecord
     */
    public SCourseJoinRecord(Integer id, Integer courseId, Integer uId, Timestamp joinTime) {
        super(SCourseJoin.S_COURSE_JOIN);

        set(0, id);
        set(1, courseId);
        set(2, uId);
        set(3, joinTime);
    }
}
