/**
 * This class is generated by jOOQ
 */
package com.wenwu.tables.tables.records;


import com.wenwu.tables.tables.SCourseQuestion;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SCourseQuestionRecord extends UpdatableRecordImpl<SCourseQuestionRecord> implements Record5<Integer, String, Timestamp, Integer, Integer> {

    private static final long serialVersionUID = 737749474;

    /**
     * Setter for <code>db_wenwu.s_course_question.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course_question.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_wenwu.s_course_question.content</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course_question.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db_wenwu.s_course_question.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course_question.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>db_wenwu.s_course_question.u_id</code>.
     */
    public void setUId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course_question.u_id</code>.
     */
    public Integer getUId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>db_wenwu.s_course_question.ch_id</code>.
     */
    public void setChId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_wenwu.s_course_question.ch_id</code>.
     */
    public Integer getChId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Timestamp, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Timestamp, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SCourseQuestion.S_COURSE_QUESTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SCourseQuestion.S_COURSE_QUESTION.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return SCourseQuestion.S_COURSE_QUESTION.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return SCourseQuestion.S_COURSE_QUESTION.U_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return SCourseQuestion.S_COURSE_QUESTION.CH_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getUId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getChId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseQuestionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseQuestionRecord value2(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseQuestionRecord value3(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseQuestionRecord value4(Integer value) {
        setUId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseQuestionRecord value5(Integer value) {
        setChId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SCourseQuestionRecord values(Integer value1, String value2, Timestamp value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SCourseQuestionRecord
     */
    public SCourseQuestionRecord() {
        super(SCourseQuestion.S_COURSE_QUESTION);
    }

    /**
     * Create a detached, initialised SCourseQuestionRecord
     */
    public SCourseQuestionRecord(Integer id, String content, Timestamp createTime, Integer uId, Integer chId) {
        super(SCourseQuestion.S_COURSE_QUESTION);

        set(0, id);
        set(1, content);
        set(2, createTime);
        set(3, uId);
        set(4, chId);
    }
}
