/**
 * This class is generated by jOOQ
 */
package com.wenwu.tables.tables.records;


import com.wenwu.tables.tables.SUserAccount;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SUserAccountRecord extends UpdatableRecordImpl<SUserAccountRecord> implements Record11<Integer, String, String, String, String, String, String, String, Timestamp, String, Integer> {

    private static final long serialVersionUID = 265823188;

    /**
     * Setter for <code>db_wenwu.s_user_account.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_wenwu.s_user_account.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_wenwu.s_user_account.openid</code>.
     */
    public void setOpenid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_wenwu.s_user_account.openid</code>.
     */
    public String getOpenid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db_wenwu.s_user_account.wx_name</code>.
     */
    public void setWxName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_wenwu.s_user_account.wx_name</code>.
     */
    public String getWxName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>db_wenwu.s_user_account.r_name</code>.
     */
    public void setRName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_wenwu.s_user_account.r_name</code>.
     */
    public String getRName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>db_wenwu.s_user_account.avatar</code>.
     */
    public void setAvatar(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_wenwu.s_user_account.avatar</code>.
     */
    public String getAvatar() {
        return (String) get(4);
    }

    /**
     * Setter for <code>db_wenwu.s_user_account.email</code>.
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_wenwu.s_user_account.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>db_wenwu.s_user_account.pwd</code>.
     */
    public void setPwd(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>db_wenwu.s_user_account.pwd</code>.
     */
    public String getPwd() {
        return (String) get(6);
    }

    /**
     * Setter for <code>db_wenwu.s_user_account.token</code>.
     */
    public void setToken(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>db_wenwu.s_user_account.token</code>.
     */
    public String getToken() {
        return (String) get(7);
    }

    /**
     * Setter for <code>db_wenwu.s_user_account.last_login_time</code>.
     */
    public void setLastLoginTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>db_wenwu.s_user_account.last_login_time</code>.
     */
    public Timestamp getLastLoginTime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>db_wenwu.s_user_account.last_login_ip</code>.
     */
    public void setLastLoginIp(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>db_wenwu.s_user_account.last_login_ip</code>.
     */
    public String getLastLoginIp() {
        return (String) get(9);
    }

    /**
     * Setter for <code>db_wenwu.s_user_account.status</code>.
     */
    public void setStatus(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>db_wenwu.s_user_account.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, String, String, String, String, Timestamp, String, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, String, String, String, String, Timestamp, String, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SUserAccount.S_USER_ACCOUNT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SUserAccount.S_USER_ACCOUNT.OPENID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SUserAccount.S_USER_ACCOUNT.WX_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SUserAccount.S_USER_ACCOUNT.R_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SUserAccount.S_USER_ACCOUNT.AVATAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SUserAccount.S_USER_ACCOUNT.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SUserAccount.S_USER_ACCOUNT.PWD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return SUserAccount.S_USER_ACCOUNT.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return SUserAccount.S_USER_ACCOUNT.LAST_LOGIN_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return SUserAccount.S_USER_ACCOUNT.LAST_LOGIN_IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return SUserAccount.S_USER_ACCOUNT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getWxName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPwd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getLastLoginTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getLastLoginIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserAccountRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserAccountRecord value2(String value) {
        setOpenid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserAccountRecord value3(String value) {
        setWxName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserAccountRecord value4(String value) {
        setRName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserAccountRecord value5(String value) {
        setAvatar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserAccountRecord value6(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserAccountRecord value7(String value) {
        setPwd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserAccountRecord value8(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserAccountRecord value9(Timestamp value) {
        setLastLoginTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserAccountRecord value10(String value) {
        setLastLoginIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserAccountRecord value11(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserAccountRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Timestamp value9, String value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SUserAccountRecord
     */
    public SUserAccountRecord() {
        super(SUserAccount.S_USER_ACCOUNT);
    }

    /**
     * Create a detached, initialised SUserAccountRecord
     */
    public SUserAccountRecord(Integer id, String openid, String wxName, String rName, String avatar, String email, String pwd, String token, Timestamp lastLoginTime, String lastLoginIp, Integer status) {
        super(SUserAccount.S_USER_ACCOUNT);

        set(0, id);
        set(1, openid);
        set(2, wxName);
        set(3, rName);
        set(4, avatar);
        set(5, email);
        set(6, pwd);
        set(7, token);
        set(8, lastLoginTime);
        set(9, lastLoginIp);
        set(10, status);
    }
}
